### PR TITLE
[FEAT] Validation Helper

### PR DESCRIPTION
**Pull request by Connor-Bernard**
# General Info

- [Pivotal Tracker Story](https://www.pivotaltracker.com/story/show/187444699)
- [ ] Breaking?

# Changes

- Add validation helper module.
- Add validation error.
- Add test coverage for new module.

# Testing

- `spec/Helpers/canvas_validation_helper_spec.rb`

# Documentation

All functions in the module are documented with rdoc comments.

# Checklist

- [x] Name of branch corresponds to story

### CODE REVIEW

**Review by cynthia-lixinyi — COMMENTED** [review]
LGTM

**Review by cynthia-lixinyi — APPROVED** [review]
LGTM

**Review by armandofox — COMMENTED** [review]
couple comments:
- don't use mixed case in directory names.  use `app/errors` not `app/Errors`.  different OSs treat mixed case differntly.
- not sure i'd advise creating a directory called `errors` - is there really no other good place this code should go?  (see module 5.8 "Other kinds of code" in textbook/cs169a videos for some ideas)

**Review by ekandell — APPROVED** [review]
LGTM

**Pull request merged**
