### PR TITLE
FEAT: Structure users controller

### PR DESCRIPTION
**Pull request by Sep26**
# General Info

- [Pivotal Tracker Story](https://www.pivotaltracker.com/story/show/########)
- [ ] Breaking?

# Changes

Explain your changes here (in such a way that you would understand why you made them a year from now).
Structured the users controller with bugs i had fixed such as not having plural form

# Testing

Explain how you tested your changes.  If testing is not necessary, explain why.

# Documentation

Does this PR require documentation.  If so, explain where it can be found.

# Checklist

- [ ] Name of branch corresponds to story

### CODE REVIEW

**Review by Connor-Bernard — APPROVED** [review]
LGTM

**Comment by zee6197** [comment]
Good job!

**Review by zee6197 — APPROVED** [review]
Good work!

**Review by Reimirno — APPROVED** [review]
All good.

`nit`: might want to do empty line at the end of every file. Your formatter should help you do it.

**Pull request merged**
